### ISSUE TITLE
Folders depth

### ISSUE THREAD

**Issue by crivotz** [benwainwright/fzf-project#6]
Possibility to increase the depth of displayed folders inside a workspace

ExampleWorkspace
├── Customer1
│ ├── ProjectA
│ └── ProjectB
├── Customer2
│ ├── ProjectC
│ └── ProjectD

Now if I set g:fzfSwitchProjectWorkspaces on 'ExampleWorkspace" the :FzfSwitchProject command show me "Customer1" and "Customer2".
The goal would be to show the list of projects: "ProjectA", "ProjectB", "ProjectC", "ProjectD"

Thanks Mauro

**Comment by benwainwright** [comment]
Hey there! 

Thanks for your suggestion. I quite like this idea. Just to be clear though, I'm assuming you want it to *stop* at ProjectA, and not list any containing directories?

So taking your example and expanding it a little:

```
ExampleWorkspace
|___Customer1
           |_______ ProjectA
                        |_______Src
                        |_______Docs
                        |_______Config

           |_______ ProjectB
                        |_______Lib
                        |_______Docs
                        |_______Config
|___Customer2
           |_______ ProjectC
                        |_______Src
                        |_______Docs
                        |_______Config
```

You would still want the list to contain

* ProjectA
* ProjectB
* ProjectC

and not any of the containing folders such as

* Src
* Lib
* Docs

etc?

**Comment by crivotz** [comment]
Exactly, it could be considered as parameter:

Default 0 -> display Customer1, Customer2
-1            -> display ProjectA, ProjectB, ProjectC
and so on

I also understand that it could be a problem if different workspaces need different depth parameters

**Comment by alec-gibson** [comment]
@crivotz not sure if this is really what you were looking for, but I modified fzf-project so it recursively searches for git projects inside workspaces, and that behavior is exactly the way I like it. By searching for git projects, you don't need to worry about what depth they are at.

If you're curious, I accidentally made a PR (so you can look at it to see the diff): https://github.com/benwainwright/fzf-project/pull/9
I also have a fork, which you can use if you want to try this behavior out: https://github.com/alec-gibson/fzf-project

One consideration with this behavior, is that it does not allow you to open non-git projects using FzfSwitchProject. Also, if you add workspaces to the list which contain non-git projects,  that might slow down FzfSwitchProject, because it will exhaustively recurse into every subdirectory looking for a git project. This does not bother me - my workspaces only contain git projects. One way to fix it would be to separate "git workspaces" where fzf-project will recursively search for git projects, and "non-git workspaces" which use the fzf-project's current logic instead.

**Comment by benwainwright** [comment]
I've been discussing this with @alec-gibson on Reddit; but I've just raised a PR that basically implements the behaviour requested on this ticket, but provides the facility to exhaustively search for `.git` folders if necessary:

https://github.com/benwainwright/fzf-project/pull/11

@alec-gibson if you are happy that this PR covers your use case, I'll merge it?

**Comment by benwainwright** [comment]
@crivotz Sorry it took me so long to do this: your use case is now covered by the following setting:

```vim
let g:fzfSwitchProjectProjectDepth = 2
```

See the README for a full description of that setting.

Note that if all your projects are `git` projects, you can just set the above to `'infinite'` and it will just recurse until it finds the project containing the `.git` folder.

**Comment by crivotz** [comment]
Thanks mate 😄
